account/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "account"

urlpatterns = [
    path('registration/', views.registration, name="registration"),
    path('', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    url('profile/(?P<id>[0-9]+)/', views.profile, name="profile"),
    url('fav/(?P<id>[0-9]+)/', views.fav, name="fav"),
    path('modify/', views.update_account, name="modify")
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.urls import path,include
from django.views.decorators.csrf import csrf_exempt
from rest_framework.authtoken.views import obtain_auth_token

from . import views

app_name = 'api'


urlpatterns = [
    # Shops
    url('shops/', views.ShopListAPIView.as_view(), name="shopslist"),
    url(r'^newshop/$', views.ShopCreateAPIView.as_view(), name="new_shop"),
    url('detail/(?P<shop_id>[0-9]+)/', views.ShopDetailAPIView.as_view(), name="shop_detail"),
    url('edit/(?P<pk>[0-9]+)/', views.ShopRetrieveAPIView.as_view(), name="shop_retrieve"),
    
    # Contact
    url('contact/', views.ContactAPIView.as_view(), name="contact"),

    # Reviews
    url('reviews/', views.ReviewListAPIView.as_view(), name="reviews"),
    url('newreview', views.ReviewCreateAPIView.as_view(), name="new_review"),
    url('deletereview/(?P<rev_id>[0-9]+)', views.ReviewDeleteAPIView.as_view(), name="delete_review"),
    
    # Category
    url('category/', views.CategoryListAPIView.as_view(), name="category"),
    path('cat/<str:cat>/', views.CategoryAPIView.as_view(), name="category"),

    # Account
    url('accounts/', views.AccountListAPIView.as_view(), name="accounts"),
    url('register/', views.RegisterAPIView.as_view(), name="new_account"),
    url('login/', views.UserLoginAPIView.as_view(), name="login"),
    url('logout/', views.UserLogoutAPIView.as_view(), name="logout"),
    path('token/', views.tokenAPI.as_view(), name='token'),
    path('profile/<str:username>/', views.AccountProfileAPIView.as_view(), name="profile"),
    path('modifyaccount/<str:username>/', views.ModifyAccountAPIView.as_view(), name="modify_account"),
]

contact/urls.py
from django.urls import path
from . import views

app_name = "contact"

urlpatterns = [
    path('', views.contact, name="contact"),
    
]

mainshop/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "mainshop"

urlpatterns = [
   url(r'^$', views.home, name='home'),
   url(r'^(?P<shop_id>[0-9]+)/$', views.detail, name='detail'),
   path('newshop/', views.new_shop, name="newshop"),
   url('changeshop/(?P<id>[0-9]+)/', views.change_shop, name="change_shop"),
   url('deleteshop/(?P<id>[0-9]+)/', views.delete_shop, name="delete_shop"),  
   url('review/(?P<id>[0-9]+)/', views.review, name='review'),
   path('remove_review', views.remove_review, name='remove_review'),
   url('like/(?P<shop_id>[0-9]+)/(?P<review_id>[0-9]+)/', views.like_rev, name="likereview"),
   path('search/', views.searchShop, name='search_results'),
   path('category/<str:cat>/', views.category, name='category'),
   path('addcategory/', views.add_category, name='add_category'),
   path('category_list', views.category_list, name='category_list'),
   path('deletecategory/<str:cat>/', views.delete_category, name="delete_category"),  

   
]

shopreviews/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from rest_framework import routers
from api import views

from django.conf.urls.static import static
from django.conf import settings

def handler404(request,exception):
    return HttpResponseRedirect(reverse("mainshop:home"))


urlpatterns = [
    path('account/', include('account.urls')),
    path('contact/', include('contact.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('mainshop.urls')),
    
    
       
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mainshop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    image =  models.URLField(default=None, null=True)

    def __str__(self):
        # Return the name of the shop
        return self.name
        

class Shop(models.Model):
    # Fields for the shops table
    name = models.CharField(max_length=100) 
    website = models.CharField(max_length=100)
    categ = models.CharField(max_length=30, default="category", null=True)
    averageRating = models.FloatField(default=0)
    logo = models.URLField(default=None, null=True)
    
    

    def __str__(self):
        # Return the name of the shop
        return self.name


class Review(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.TextField(max_length=50, null=False)
    comment = models.TextField(max_length=5000, null=False)
    
    rating = models.FloatField(default=0, null=False)
    date_pub = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    rev_date =  models.DateField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name="likes_review")
    

    def __str__(self):
        return self.title

    

mainshop/forms.py
from django import forms
from .models import *

categories = Category.objects.all().values_list('name', 'name')
categories_list = []

for item in categories:
    categories_list.append(item)


# Shop form
class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ['name', 'website', 'logo', 'categ']

        widgets={
            'categ': forms.Select(choices=categories_list, attrs={'class': 'form-control'}),
        }
        
# Review form
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'comment', 'rating']


# Category form
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'image']

mainshop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from .forms import *
from account.models import Account
from django.contrib.auth.models import User
from django.db.models import Avg, Q
from django.contrib import messages
from django.urls import reverse
from django.views.generic import RedirectView
from http import HTTPStatus
import collections
from django.views.generic import ListView
from datetime import datetime 


""" Main site """
def home(request):
    return render(request, 'mainshop/index.html')

""" This view is the --> Shop detail """
def detail(request, shop_id):
    # Get the shop and the User
    shop = Shop.objects.get(id=shop_id)
    user = request.user.id
    
    # Set the variables
    account= None
    favorited=False
    
    # Default display for reviews
    reviews = Review.objects.filter(shop=shop_id).order_by("-date_pub")
    
    if request.user.is_authenticated:
        # Get the account linked to the User
        account = Account.objects.get(user=user)
        
        # Add shop to account favorite (don't consider the other POST FORM in the template)
        if request.method == 'POST' and "orderform" not in request.POST and "likeform" not in request.POST:
            # If the shop is already in favs remove it after click
            if account.favourite.filter(id=shop_id).exists():
                account.favourite.remove(shop)
            else:
                # If the shop is not in favs add it after click
                account.favourite.add(shop)

        # For button changing
        if account.favourite.filter(id=shop_id).exists():
            favorited = True
        else:
            favorited = False

    # Change order reviews
    if request.method == 'POST' and "orderform" in request.POST:
        choice = request.POST["order"]
        if choice == "Title":
            reviews = Review.objects.filter(shop=shop_id).order_by("title")
            select = "Title"
        elif choice == "Date":
            reviews = Review.objects.filter(shop=shop_id).order_by("-date_pub")
        elif choice == "BestRating":
            reviews = Review.objects.filter(shop=shop_id).order_by("-rating")
            select = "BestRating"
        elif choice == "LowRating":
            reviews = Review.objects.filter(shop=shop_id).order_by("rating")
            select = "LowRating"
     
    # Reviews details
    number_r = reviews.count()
    average = reviews.aggregate(Avg("rating"))["rating__avg"]
           
    if average == None:
        average = 0
    average = round(average, 2)
      
    error = None
    if number_r==0:
        error = "Sadly there's no reviews yet"
            
    context = {
        "shop": shop,
        "reviews": reviews,
        "average": average,
        "total" : number_r,
        "error" : error,
        "favorited": favorited
        
    }
    
    return render(request, 'mainshop/detail.html', context)


""" This view allow the User to give a like to the reviews """
def like_rev(request, shop_id, review_id):
    reviews = Review.objects.get(id=review_id)
    # Check if the user already liked the review
    if reviews.likes.filter(id=request.user.id).exists():
        reviews.likes.remove(request.user)
    else:
        reviews.likes.add(request.user)
    
    return redirect("mainshop:detail", shop_id)

""" Add new shop """
def new_shop(request):
    # Allow to do this only to the superuser (Chiara)
    if request.user.is_superuser:
        if request.method == "POST":
            form = ShopForm(request.POST or None)

            # Check if the form is ok
            if form.is_valid():
                name = form.cleaned_data.get('name')
                
                # Check if the shop already exist
                if Shop.objects.filter(Q(name=name)):
                    error = 'A shop with this name already exist.'
                    return render(request, 'mainshop/newshop.html', {'form': form, 'error': error}, status=HTTPStatus.FOUND)

                # Save data
                data = form.save(commit=False)
                data.save()
                return redirect("mainshop:home")
        else:
            form = ShopForm()
        return render(request, 'mainshop/newshop.html', {"form": form, "controller": "Add new Shop"})
    
    # If the account is not the admin
    else:
        return redirect("mainshop:home")


""" Change information about the shop """
def change_shop(request, id):
    if request.user.is_superuser:
        # Take the id to identify the shop
        shop = Shop.objects.get(id=id)
        if request.method == "POST":
            form = ShopForm(request.POST or None, instance=shop)
            
            if form.is_valid():
                data = form.save(commit=False)
                data.save()
                return redirect("mainshop:detail", id)
        else:
            form = ShopForm(instance=shop)
        return render(request, 'mainshop/changeshop.html', {"form": form})
    
    # If the account is not the admin
    else:
        return redirect("mainshop:home")


""" Delete a shop """
def delete_shop(request, id):
    if request.user.is_superuser:
        #Get the shop by the id
        shop = Shop.objects.get(id=id)

        # Delete
        shop.delete() 
        return redirect ('mainshop:home')

    # If the account is not the admin
    else:
        return redirect("mainshop:home")


""" This view define a category with its shops """
def category(request, cat):
    # Get the category
    category_shop = Shop.objects.filter(categ=cat).order_by('name')
      
    for s in category_shop:
        shop = Shop.objects.get(id=s.id)
        reviews = Review.objects.filter(shop=s.id).order_by("-comment")
        average = reviews.aggregate(Avg("rating"))["rating__avg"]
        
        if average == None:
            average = 0
        
        average = round(average, 2)
        s.averageRating=average
      
        s.save()
    
    return render(request, 'mainshop/category.html', { 'cat':cat, 'shops':category_shop })

""" Display all the categories """
def category_list(request):
    cat_list = Category.objects.all().order_by('name')
    return render(request, 'mainshop/category_list.html', { 'list':cat_list })

""" Insert a new category """
def add_category(request):
    # This can be done only by the superuser
    if request.user.is_superuser:
        if request.method == "POST":
            form = CategoryForm(request.POST or None)

            # Check if the form is ok
            if form.is_valid():
                name = form.cleaned_data.get('name')
                
                # Check if the shop already exist
                if Category.objects.filter(Q(name=name)):
                    error = 'A category with this name already exist.'
                    return render(request, 'mainshop/newshop.html', {'form': form, 'error': error})

                data = form.save(commit=False)
                data.save()
                return redirect("mainshop:home")
        else:
            form = CategoryForm()
        return render(request, 'mainshop/add_category.html', {"form": form, "controller": "Add new category"})
    
    # If the account is not the admin
    else:
        return redirect("mainshop:home")


""" DELETE CATEGORY """
def delete_category(request, cat):
    if request.user.is_superuser:
        #Get the shop by the id
        c = Category.objects.get(name=cat)

        # Delete
        c.delete() 
        return redirect ('mainshop:category_list')

    # If the account is not the admin
    else:
        return redirect("mainshop:home")

""" ADD A REVIEW """
def review(request, id):
    # Only a user can add a review
    if request.user.is_authenticated:
        shop = Shop.objects.get(id=id)

        if request.method == "POST":
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.title = request.POST['title']
                data.comment = request.POST["comment"]
                data.rating = request.POST["rating"]
                data.user = request.user
                data.shop = shop
                data.save()

                return redirect("mainshop:detail", id)
        else:
            form = ReviewForm()
        return render(request, 'mainshop/newreview.html', {"form": form, "shops":shop})
    else:
        return redirect("account:login")


""" Search view """
def searchShop(request):
    # Variables
    count_s=None
    # Query
    query = request.GET.get('q')
    shop = Shop.objects.filter(Q(name__icontains=query))
  
    if shop is not None:
        count_s = shop.count()
    
    context = {
        "query": query,
        "shops": shop,
        "tot" : count_s,
    }

    return render(request, 'mainshop/search_results.html', context)


""" Remove review """
def remove_review(request):
    if request.method == 'POST':
        try:
            review_id = request.POST['review_id']
        except:
            error = "Something wrong with your request."
            return HttpResponseRedirect(reverse('mainshop:home', args=(error,)))
        try:
            review = Review.objects.get(id=review_id)
            print(review.shop.id)
        except:
            return HttpResponseRedirect(reverse('mainshop:detail', args=(review.shop.id,)))
        review.delete()
        return HttpResponseRedirect(reverse('mainshop:detail', args=(review.shop.id,)))
  
    return HttpResponseRedirect(reverse('mainshop:detail'))

mainshop/templates/mainshop/add_category.html
{% extends 'mainshop/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<style>
    #modify-button{
      color: #ef22c2;
      background-color: #faf9f9;
      letter-spacing: 0px;
      padding: 24px 20px;
      border-radius: 10px;
      font-size: 22px;
     margin-top: 20px;
    }
  
    
  </style>


<div class="container">
    <div class="card" style="background: rgb(240,236,238);
    background: linear-gradient(365deg, rgba(240,236,238,1) 0%, rgba(250,249,250,1) 35%, rgba(255,255,255,1) 100%); border:1px;">
        <div class="card-body">
            <h3 class="text-center" style="font-family: unset;">{{ controller }}</h3>
            <form action="" method="POST">
                {% csrf_token %}

                {% if error %}
				<font color="red">{{error}}</font>
				{% endif %}

                {{ form | crispy }}
                <p></p>
                
                <input type="submit" value="{{ controller }}" class="btn btn-danger" id="modify-button">
            </form>
        </div>
    </div>
</div>

{% endblock %}

mainshop/templates/mainshop/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
     
     
       
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css'  %}">
   <title>ShopTrust</title>
    
<style>
  #logout-btn{
    color: #e846c5;
    background: #f9f9f9;
    letter-spacing: 0px;
    padding: 13px 14px;
    border-radius: 10px;
    font-size: 15px;
  }

  .btn::before{
    background: #c2c2c2;
  }

  #submenu {
   border-top: 5px solid #ff33dd;
  }
   
 
</style>
  </head>
  <body>
    <header>
      <div class="header-area">
        <div class="main-header ">
           <div class="header-bottom  header-sticky mb-3 " style="background-color: rgb(255, 254, 254);">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <!-- Logo -->
                        <div class="col-xl-1 col-lg-1 col-md-1 col-sm-3">
                          <div class="logo">
                            <a href="{% url 'mainshop:home' %}"><img height=100px src="{% static 'logo3.png' %}" alt=""></a>
                          </div>
                      </div>
                        <div class="col-xl-6 col-lg-8 col-md-7 col-sm-5">
                          
                            <!-- Main-menu -->
                            <div class="main-menu f-right d-none d-lg-block" id="menu">
                                 <nav>                                                
                                    <ul id="navigation"> 
                                        <li><a href="{% url 'mainshop:home' %}">Home </a></li>
                                        <li><a href="{% url 'mainshop:category_list' %}">Shops</a>
                                          {% if user.is_superuser %}
                                            <ul class="submenu" id="submenu">
                                              <li><a href="{% url 'mainshop:category_list' %}"> Categories </a></li>
                                              <li><a href="{% url 'mainshop:newshop' %}"> Add Shop</a></li>                                                
                                            </ul>
                                            {% endif %}
                                        </li>
                                        <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                                        {% if user.is_authenticated %}
                                        <li><a href="{% url 'account:profile' user.id %}">Profile</i></a>
                                          <ul class="submenu" id="submenu">
                                            <li><a href="{% url 'account:profile' user.id %}"> My Profile</a></li>
                                            <li><a href="{% url 'account:fav' user.id %}"> Favourite shops</a></li>
                                        </ul></li>
                                        {% endif %}
                                    </ul>
                                </nav>
                                <div id="mobile-menu-wrap"></div>
                            </div>
                        </div>


                        <div class="col-xl-5 col-lg-3 col-md-3 col-sm-3 fix-card">
                           <ul class="header-right f-right d-none d-lg-block d-flex justify-content-between">
                            <ul class="header-right">
                              <li class="d-none d-xl-block">
                                  <div class="form-box f-right ">
                                    <form class="form-inline d-flex justify-content-center md-form form-sm" action="{% url 'mainshop:search_results' %}" method="get">
                                      <input class="form-control" name="q" type="text" placeholder="Search shop" aria-label="Search" style="padding: 22px 20px;">
                                      <div class="search-icon">
                                        <i class="fas fa-search "></i>
                                    </div>
                                    </form>
                                  </div>
                               </li>
                            </ul>
                            
                                                          
                            {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: black">
                                <span id="hello-msg" style="color: black; font-size: 20px;" >Hello, <strong>{{ request.user.account.username }}</strong></span>  
                              </a>
                              <div class="dropdown-menu" aria-labelledby="navbarDropdown" >
                                 <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
                              </div>
                            </li>
                            {% else %}
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'account:login' %}" style="color: black">Login <i class="fas fa-sign-in-alt"></i></a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'account:registration' %}" style="color: black">Register</a>
                            </li>
                            {% endif %}
                              </li>
                          </ul>
                      </div>
                      <!-- Mobile Menu -->
                      <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                    </div>
                </div>
           </div>
        </div>
   </div>
      <!-- Header End -->
  </header>



    {% block content %}

    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    
  </body>
</html>

mainshop/templates/mainshop/category_list.html
{% extends 'mainshop/base.html' %}


{% block content %}

<style>

#card:hover{
    
    background-color: rgb(253, 215, 248);
}

#badge-site{
        align-items: center;
        padding: 16px 20px;
        margin-top: 10px;
    }




</style>


<h2 class="text-center" style="font-family: unset; font-size: 50px;"> <strong>Categories</strong>  </h2>

<div class="container mt-4 " style="max-width: 940px;">
    
    
    {% for item in list %}
    <div class="col-md-12" >
     
    <div class="card shadow p-3" id="card" style="border: 1px solid rgb(235 105 243 / 13%); height: 140px; border: 0px; background: rgb(240,236,238); background: linear-gradient(365deg, rgba(240,236,238,1) 0%, rgba(250,249,250,1) 35%, rgba(255,255,255,1) 100%);">
        
        <div class="row">
            <div class="col-md-3">
                <div class="shadow-sm p-2 mb-1 bg-white rounded" width="50%" style="transform:translateX(-50px);     width: 170px;">
                    
                        <img class="img-fluid" src="{{ item.image }}" >
                    
                </div>
            </div>
            <div class="col-md-6 " style="padding-top: 20px;">
                <section class="header-section">
                    <h2 style="text-align: center; font-family: unset; margin-top: 5px;"><a href="{% url 'mainshop:category' item %}" style="color: #000000;" > {{ item }}</a></h2> 
                    {% if user.is_superuser %}   
                <a href="{% url 'mainshop:delete_category' item %}" onclick="return confirm('Are you sure you want to delete this?');" class="txt2" style="color:#e71aa8;     margin-left: 150px; text-align: center; font-family: unset; margin-top: 10px;">
                    Delete <strong>{{ item }}</strong>
                </a>
                {% endif %}                      
                </section>
               </div>
               <div class="col-md-2">
                <!-- BADGE SITO -->
            
                <div class="badges" data-badges="" style="    margin-top: 20px;">
                    <div class="badges__badges">
                        <div class="badge-card">
                            <a href="{% url 'mainshop:category' item %}" class="badge badge-light" id="badge-site" style="background-color: #ecc3e3;">
                                 <i class="fas fa-arrow-circle-right large"></i> </a>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
</div> 
    <br>
    {% endfor %}
</div>



{% endblock %}

mainshop/templates/mainshop/changeshop.html
{% extends 'mainshop/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<style>
    #modify-button{
      color: #ef22c2;
      background-color: #faf9f9;
      letter-spacing: 0px;
      padding: 24px 20px;
      border-radius: 10px;
      font-size: 22px;
     margin-top: 20px;
    }
  
    
  </style>

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center" style="font-family: unset;">Change settings</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" value="Submit" class="btn btn-danger" id="modify-button">
            </form>
        </div>
    </div>
</div>


{% endblock %}

mainshop/templates/mainshop/index.html
{% extends 'mainshop/base.html' %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css'  %}">



{% block content %}

<style>
    body {
 background-image: url("static/HOME3.png");
 background-color: #ffffff;
 width: 100%;
  height: 400px;
  position: fixed;
  top: 0;
  left: 0;
}
</style>
<body>
    



<div class="header-bottom  header-sticky">
    <div class="container-fluid">
        <div class="row align-items-center">
            <ul class="header-right f-right d-none d-lg-block d-flex justify-content-between" style="padding-left: 600px;">
                    <!-- Search form -->
              <div class="ml-3">            
                  <form class="form-inline d-flex justify-content-center md-form form-sm" action="{% url 'mainshop:search_results' %}" method="get">
                      <input class="form-control" name="q" type="text" placeholder="Search shop" aria-label="Search" style="border-radius: 100px; border: 1px solid #ffaff5;     margin-top: 500px;"> <i class="fas fa-search" style="margin-left: 10px; margin-top: 500px;" aria-hidden="true" type="submit"></i>
                    </form>
                      <br>
                                                        
                      <span class="txt1">
                        Do you want to add a new Shop?
                    </span>

                    <a href="{% url 'contact:contact' %}" class="txt2" style="color:#e71aa8">
                        Contact us!
                    </a>   
                 
              
            </div>
            
          </ul>
         
              
         
       
        </div>
    </div>
</div>



</body>

{% endblock %}

mainshop/templates/mainshop/newshop.html
{% extends 'mainshop/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<style>
    #modify-button{
      color: #ef22c2;
      background-color: #faf9f9;
      letter-spacing: 0px;
      padding: 24px 20px;
      border-radius: 10px;
      font-size: 22px;
     margin-top: 20px;
    }
  
    
  </style>


<div class="container">
    <div class="card" style="background: rgb(240,236,238);
    background: linear-gradient(365deg, rgba(240,236,238,1) 0%, rgba(250,249,250,1) 35%, rgba(255,255,255,1) 100%); border:1px;">
        <div class="card-body" >
            <h3 class="text-center" style="font-family: unset;">{{ controller }}</h3>
            <form action="" method="POST">
                {% csrf_token %}

                {% if error %}
				<font color="red">{{error}}</font>
				{% endif %}

                {{ form | crispy }}
                <p></p>
                <ul class="login-more p-t-40">
                                     
                    <span class="txt1">
                        Don’t find the right category?
                    </span>

                    <a href="{% url 'mainshop:add_category' %}" class="txt2" style="color:#e71aa8">
                        Add it
                    </a>
               
            </ul>
                <input type="submit" value="{{ controller }}" class="btn btn-danger" id="modify-button">
            </form>
        </div>
    </div>
</div>

{% endblock %}